import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <link
          rel="preload"
          href="/_next/static/media/57f1d33f397a70e0-s.p.0x~nu3muxhvkk.woff2"
          as="font"
          crossOrigin=""
          type="font/woff2"
        />
        <link
          rel="preload"
          href="/_next/static/media/70bc3e132a0a741e-s.p.1409xf.ylxg8g.woff2"
          as="font"
          crossOrigin=""
          type="font/woff2"
        />
        <link
          rel="preload"
          href="/_next/static/media/83afe278b6a6bb3c-s.p.0q-301v4kxxnr.woff2"
          as="font"
          crossOrigin=""
          type="font/woff2"
        />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
